name: CI-PROD

on:
  pull_request:
    branches: [ main ]  # main 브랜치에 pr 했을때 트리거
  push:
    branches: [ main ]  # main 브랜치에 push 했을때 트리거

permissions:
  contents: read # 내 코드를 읽을 수 있게(코드이동) 접근 권한을 준다.
  id-token: write   # OIDC 토큰을 발급할 수 있게 한다.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout   # 내 코드 이동 깃허브 컴퓨터로
        uses: actions/checkout@v4

      - name: Set up JDK 17   # jdk 환경 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Gradle   => gradle 설치
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew # 실행 권한 설정
        run: chmod +x ./gradlew

      - name: Run tests                          # 테스트 실행
        run: ./gradlew test --no-daemon

      - name: Generate image tag        # pr이 아닌 push 일때 이미지 태그 생성
        if: github.event_name == 'push' # 커밋 기반으로 어떤 코드 버전이 배포됐는지 정확히 추적 가능
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV # 태그란? 이미지 버전 이름

      - name: Configure AWS credentials (OIDC)  # OIDC 기반으로 역할 자격증명
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR     # 위에서 자격증명하고 ecr 로그인
        if: github.event_name == 'push'
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image    # 이미지 빌드해서
        if: github.event_name == 'push'
        run: |
          docker build -t ${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .

      - name: Push Docker image to ECR    # 이미지 ecr로 업로드
        if: github.event_name == 'push'
        run: |
          docker push ${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
